"""Generate Black Star's static service pages, guide hub, and shared footer.
Run from any directory: python3 scripts/build-pages.py
No third-party dependencies. Edit content here, then commit generated output.
"""
from pathlib import Path
from html import escape as e
import json, re
ROOT = Path(__file__).resolve().parents[1]
BASE = 'https://aetherai3.github.io/Blackstar/'
VERSION = 'soft-motion-1'
SERVICES = [
 dict(slug='websites-and-apps', key='web', title='Websites & web apps', headline='A clear home for your business. A useful tool for your team.', description='Business websites, landing pages, and custom web apps built directly with Brandon. Clear scope, responsive design, practical integrations, and a usable handoff.', intro='Help people understand your offer, get in touch, or complete a task. We design and build websites and web apps around what your business actually needs.', fit='For founders and small teams launching an offer, replacing an outdated website, or moving a manual process into a client portal or internal tool.', owner='Brandon leads design implementation, development, backend integrations, testing, and deployment. Edwin supports visual direction when the project calls for it.', outputs=[('Business websites','A responsive site with agreed pages, clear content, and a working inquiry path.'),('Landing pages','A focused page for one offer or campaign, with a clear next step.'),('Custom web apps','Portals, dashboards, or internal workflows with named user roles and integrations.')], boundaries=['Copywriting, brand redesign, product photography, and content migration are separate unless listed in your proposal.','Payments, logins, CMS features, and third-party integrations are scoped individually.','Hosting, provider usage, and ongoing updates are agreed separately from the build.'], process='We agree the pages and workflows, review the design, build a working preview, then check the approved requirements before launch.', handoff='Your approved site or app, the agreed source/access, an operating guide, and a defined support window. Ownership and recurring costs are documented in the proposal.', proof='Explore Aether AI', proofurl='https://aethersystems.net', prooftext='Brandon’s own software venture shows the technical side of the team. It is founder work, not presented as a paid Black Star client engagement.', faqs=[('Can you work on an existing website?','Yes. We first review the stack, access, and requested changes so the estimate reflects the actual work.'),('Is SEO included?','We can include technical search foundations such as page titles, metadata, and indexable content. Ongoing content, search campaigns, and ranking outcomes are separate.'),('Who owns the accounts?','We agree account and source ownership before work starts, including domain, hosting, repository, and provider responsibilities.')]),
 dict(slug='brand-and-design', key='brand', title='Brand identity & design', headline='Make your business feel like one business.', description='Brand identity and digital design for founders and small businesses. Work directly with Edwin on a clear visual direction and practical brand assets.', intro='Bring your logo, website, social content, and everyday materials into a consistent visual direction that people can recognize.', fit='For a new business finding its look, or an existing business whose materials no longer feel connected.', owner='Edwin leads creative direction and design. Brandon handles implementation when the identity carries into a website or digital product.', outputs=[('Visual identity','An agreed identity direction, color palette, typography, and logo work where included.'),('Digital materials','The specific social, web, or presentation assets your project needs.'),('Brand handoff','Approved exports and concise guidance for using the identity consistently.')], boundaries=['Concept counts, export formats, and revision rounds are written into the scope.','A new direction after approval, additional applications, and extra concepts require a change estimate.','Trademark clearance, naming research, printing, and licensing purchases are not assumed to be included.'], process='We gather references and business context, develop the agreed concepts, refine one selected direction, and prepare the final asset set.', handoff='The approved files, agreed source formats, usage notes, and a record of fonts or other licensed elements.', proof='Meet the creative lead', proofurl='../index.html#team', prooftext='Edwin leads the creative side of Black Star and runs East Coast Chromes. Discuss the relevant work and deliverables with him before choosing a direction.', faqs=[('Do I need a completely new logo?','No. We can scope a refinement or a set of supporting materials if your existing identity already works.'),('How many revisions do I get?','Our proposed starting point is two consolidated rounds on the selected direction. Your signed proposal states the actual allowance.'),('Are editable files included?','We list source files and final exports explicitly so there is no ambiguity at handoff.')]),
 dict(slug='photography-and-video', key='video', title='Photography & video', headline='Show the work. Capture the feeling.', description='Photography, brand films, automotive content, and short-form video led by Edwin. Defined shoots, clear edit counts, and delivery-ready media.', intro='Give people a closer look at your business, product, or story through photography and video made for the places you plan to use it.', fit='For brands, businesses, and creators who need a defined shoot or a focused set of content for their website, launch, or social channels.', owner='Edwin leads the shoot, creative direction, and edits. Brandon supports website or campaign integration where it is part of the project.', outputs=[('Photography','A scoped shoot and selected edited images for your agreed use.'),('Brand and automotive films','A film or sequence shaped around a brief, location, and shot list.'),('Short-form edits','A defined number of cuts, lengths, captions, and aspect ratios for your channels.')], boundaries=['Travel, locations, talent, music licensing, and special equipment are agreed before production.','Raw footage, extra formats, and additional edits are included only when listed.','A reshoot or changed brief is a new production decision, not automatically an edit round.'], process='We plan the use, shot list, and logistics, capture the material, review the agreed edits, and deliver the approved exports.', handoff='The contracted image/video exports, agreed usage details, and clear filenames. Raw files or project files are included only as agreed.', proof='Explore East Coast Chromes', proofurl='https://eastcoastchromes.com', prooftext='See Edwin’s automotive media brand for a direct look at the creative side of the team. The site links to the real venture.', faqs=[('Can you travel for a shoot?','Location, availability, travel costs, and scheduling are confirmed during scoping. We do not promise every location or date.'),('Can the footage be used on multiple platforms?','Yes, when the needed formats and usage are included in the brief. List the channels before we plan the shoot.'),('What if plans change?','We agree contingencies for scheduling, weather, and reshoots before production so changes can be handled clearly.')]),
 dict(slug='social-content', key='social', title='Social content & management', headline='A clearer plan for showing up.', description='Social content planning, platform-ready creative, and publishing support for small teams. Defined channels, asset counts, approvals, and responsibilities.', intro='Turn scattered posting into a manageable content plan, with creative that fits your brand and a clear process for getting it approved.', fit='For businesses with something to share who need help planning, preparing, or consistently publishing their content.', owner='Edwin leads the content direction, creative, and calendar. Brandon supports technical scheduling connections when separately scoped.', outputs=[('Content planning','A calendar around agreed themes, channels, and business priorities.'),('Platform-ready creative','The agreed number of posts, captions, reels, or supporting assets.'),('Publishing support','Scheduling and posting responsibilities defined around the access and approvals you provide.')], boundaries=['Community management, customer-service replies, and round-the-clock monitoring are separate.','Paid advertising, influencer outreach, and new photography/video shoots are not assumed to be included.','Follower growth, reach, and viral results are not guaranteed.'], process='We agree the channels and monthly output, prepare a review batch, collect consolidated feedback, and publish or hand off approved content.', handoff='An agreed content batch or calendar, final assets, and a concise account of what was completed. Ongoing work is renewed against a defined scope.', proof='Talk with Edwin', proofurl='https://instagram.com/5.0win', prooftext='Start a direct conversation with the creative lead about your channels and the content you already have.', faqs=[('Can you use our existing photos and videos?','Yes, if you have permission to use them and they fit the brief. We assess whether additional production is needed.'),('Do you post for us?','We can scope publishing support, or deliver content for your team to post. The proposal identifies who approves and who publishes.'),('Is this an unlimited content subscription?','No. We agree the platforms, deliverable counts, review rounds, and service period.')]),
 dict(slug='ai-and-automation', key='automation', title='AI agents & automation', headline='Make everyday work easier to run.', description='Practical AI assistants and workflow automation built by Brandon. Connect named tools, handle exceptions, and keep people in control of important actions.', intro='Connect the tools you already use and reduce repetitive work with a process built around your actual day-to-day operations.', fit='For small teams repeating the same intake, onboarding, routing, or administrative tasks across several systems.', owner='Brandon owns discovery, backend development, integrations, testing, deployment, and the technical handoff.', outputs=[('Connected workflows','Named triggers and actions between agreed tools, with clear failure handling.'),('AI assistants','A bounded assistant for a specific task, with defined inputs and review points.'),('Operational handoff','Setup documentation, usage limits, and the agreed monitoring or support process.')], boundaries=['We scope the systems and permissions first; we do not promise compatibility with every tool.','Provider fees, usage, data cleanup, and ongoing monitoring are defined separately.','AI output is not guaranteed to be correct. Consequential actions need appropriate human review and clear limits.'], process='We map the current task, identify the safest useful improvement, build a limited workflow, and test normal inputs, errors, retries, and handoff.', handoff='The agreed workflow and source/access, configuration notes, failure/recovery steps, and visibility into ongoing provider costs.', proof='Explore Aether AI', proofurl='https://aethersystems.net', prooftext='Brandon’s own venture focuses on software and AI tooling. Your agency project still receives its own scope, constraints, and acceptance checks.', faqs=[('Does every automation need AI?','No. Straightforward rules are often enough. We use AI only where it helps the agreed task.'),('Can it work with our current tools?','We review the providers, APIs, account access, and usage limits before promising an integration.'),('Can an agent send messages or change records?','Only within the permissions and approval rules agreed for the workflow. We define those boundaries before deployment.')]),
 dict(slug='marketing-and-launches', key='marketing', title='Marketing & launch support', headline='Bring your next offer together.', description='Launch planning, campaign creative, and coordinated website and social assets. A focused freelance team for a defined launch, with clear responsibilities.', intro='Get the page, creative, and content moving toward the same goal, with a manageable launch plan and clear ownership of each piece.', fit='For a founder or business preparing a new offer, product announcement, or coordinated refresh across web and social.', owner='Edwin leads campaign creative and content. Brandon leads landing pages, technical integrations, and launch checks. One founder is named as your project lead.', outputs=[('Launch planning','A brief, sequence, deliverable list, and ownership of the agreed launch tasks.'),('Campaign assets','The specific copy/design/content work included in your approved scope.'),('Coordinated web and social','A connected set of approved pages and assets ready for the channels you choose.')], boundaries=['Advertising spend, ongoing ad buying, PR placements, and influencer partnerships are separate.','Sales volume, press coverage, conversion lifts, and launch results are not guaranteed.','New channels, added campaigns, and continued support after launch need their own scope.'], process='We define the offer and audience, agree the asset list, produce and review the work, then check links, forms, and publishing responsibilities before launch.', handoff='Approved launch assets, the agreed live pages, a completed release checklist, and a clear next-step or ongoing-support plan.', proof='See the team’s work & ventures', proofurl='../index.html#portfolio', prooftext='Explore the existing ventures for examples of the team’s creative and technical work. We do not present them as proven campaign results.', faqs=[('Can you help with just one part of a launch?','Yes. A landing page or asset batch can be a focused engagement rather than a full campaign.'),('Do you buy ads?','Paid campaign management is not included by default. Any channel, access, spend, and management responsibility must be agreed first.'),('What happens after launch?','We complete the contracted handoff. Reporting, improvements, and recurring support can be scoped as a separate phase.')])
]
DOCS = [
 ('Agency & website specification','docs/BLACK-STAR-AGENCY-SPEC.md','The brand, services, protected links, and original website requirements.'),
 ('Contact & Resend plan','docs/CONTACT-AND-RESEND-SPEC.md','The current email-draft flow and proposed direct email integration.'),
 ('Business operating plan','docs/business/OPERATING-SPEC.md','Founder responsibilities and the proposed path from inquiry to delivery.'),
 ('Client portal & integrations','docs/business/PORTAL-AND-INTEGRATIONS.md','Planned assets, reviews, approvals, and invoice tracking. Not a live portal.'),
 ('Scope & delivery templates','docs/business/SCOPE-AND-DELIVERY.md','Working defaults for revisions, changes, reviews, and handoffs.'),
 ('Search visibility & proof','docs/business/VISIBILITY-AND-PROOF.md','The SEO/GEO roadmap and standards for credible case studies.'),
 ('Website verification record','docs/VERIFICATION.md','Dated checks from the original website overhaul; not a current audit of every feature.'),
 ('Asset provenance','assets/README.md','Where the supplied identity, photographs, and site artwork came from.'),
 ('Service pages & search release','docs/SERVICE-PAGES-AND-SEARCH.md','This release’s content decisions, search setup, and verification boundaries.')
]
AMBIENT='<div class="ambient-field" aria-hidden="true"><div class="ambient-dots"></div><div class="ambient-glow"></div><div class="ambient-dots-lit"></div></div>'
def link(href,label,cls=''):
 return f'<a href="{e(href,quote=True)}"'+(f' class="{cls}"' if cls else '')+f'>{e(label)}</a>'
def header(prefix):
 def item(url,title,desc):
  return f'<a class="dropdown-link" href="{e(url,quote=True)}"><strong>{e(title)}</strong><span>{e(desc)}</span></a>'
 def dropdown(id,title,content):
  return f'<details class="nav-dropdown" id="nav-{id}"><summary>{title}<span class="nav-chevron" aria-hidden="true">⌄</span></summary><div class="nav-flyout">{content}</div></details>'
 services=''.join(item(prefix+'services/'+x['slug']+'/',x['title'],x['outputs'][0][1]) for x in SERVICES)
 service_content='<p class="dropdown-eyebrow">SIX WAYS FORWARD</p><div class="dropdown-grid">'+services+'</div>'+link(prefix+'index.html#services','See all services →','dropdown-bottom')
 work_content='<div class="dropdown-feature"><p class="dropdown-eyebrow">WORK & VENTURES</p><h3>Creative instinct.<br>Technical depth.</h3><p>Explore the businesses and work behind the founders.</p></div><div class="dropdown-grid">'+item('https://aethersystems.net','Aether AI ↗','Brandon’s software and AI venture.')+item('https://eastcoastchromes.com','East Coast Chromes ↗','Edwin’s automotive media brand.')+item('https://foodtrackers.org','Food Trackers ↗','Meal planning, macros, and calorie tracking.')+item(prefix+'index.html#portfolio','Explore our work →','See the full project collection.')+'</div>'
 about_content='<div class="dropdown-feature"><p class="dropdown-eyebrow">INDEPENDENT CREATIVE & DIGITAL</p><h3>Directly with<br>Edwin and Brandon.</h3><p>Two founders. Clear ownership. A direct line to the people making it happen.</p></div><div class="dropdown-grid">'+item(prefix+'index.html#team','Meet the founders','Creative production and full-stack development.')+item(prefix+'how-we-work/','How we work','From a focused brief to a complete handoff.')+item('https://instagram.com/5.0win','Edwin / @5.0win ↗','Creative direction, photography, and video.')+item('https://instagram.com/zo.trades2','Brandon / @zo.trades2 ↗','Websites, backend systems, and billing.')+'</div>'
 resources='<p class="dropdown-eyebrow">A CLEARER START</p><div class="dropdown-grid">'+item(prefix+'guides/','Guides & documentation','All services, specifications, and planning notes.')+item(prefix+'how-we-work/#boundaries','Scope & boundaries','What is included, what changes, and how we agree it.')+item('https://github.com/AetherAI3/Blackstar/blob/main/docs/business/SCOPE-AND-DELIVERY.md','Delivery templates ↗','Open working templates for reviews and handoffs.')+item(prefix+'index.html#contact','Start a conversation','Tell us your goal and choose a service.')+'</div>'+link(prefix+'guides/','Explore all documentation →','dropdown-bottom')
 return f'<header class="site-header" id="navbar"><nav class="nav-container" aria-label="Main navigation"><a href="{prefix}index.html#hero" class="nav-logo" aria-label="Black Star Entertainment home"><img src="{prefix}assets/black-star-logo.svg" alt="Black Star Entertainment" width="1299" height="544"></a><button class="hamburger" id="hamburger" aria-controls="nav-menu" aria-expanded="false" aria-label="Open navigation"><span></span><span></span></button><div class="nav-menu" id="nav-menu">'+dropdown('services','Services',service_content)+dropdown('work','Our work',work_content)+dropdown('about','About us',about_content)+dropdown('guides','Guides',resources)+link(prefix+'index.html#contact','Start a project ↗','nav-cta')+'</div></nav></header>'
def guide(prefix):
 return (ROOT/'scripts/project-guide.html').read_text().replace('__HOME__',prefix+'index.html').replace('__PROCESS__',prefix+'how-we-work/')
def footer(prefix):
 services=''.join(link(prefix+'services/'+x['slug']+'/',x['title']) for x in SERVICES)
 docs=''.join(link('https://github.com/AetherAI3/Blackstar/blob/main/'+path,title) for title,path,_ in DOCS)
 return f'''<footer id="footer" data-ambient>{AMBIENT}<div class="container">
<div class="footer-invitation"><div><p class="eyebrow">A CLEAR NEXT STEP</p><h2>Tell us what<br><em>you have in mind.</em></h2><p>A focused project or an idea taking shape. We’ll work out the scope with you.</p></div><div class="footer-actions">{link(prefix+'index.html#contact','Start a project ↗','btn btn-gold')}{link(prefix+'how-we-work/','How we work →','text-link')}</div></div>
<div class="footer-directory"><div><a href="{prefix}index.html#hero" class="footer-brand"><img src="{prefix}assets/black-star-logo.svg" alt="Black Star Entertainment" width="1299" height="544"></a><p>Independent creative & digital.<br>Directly with Edwin and Brandon.</p><div class="footer-socials">{link('https://instagram.com/5.0win','Edwin / @5.0win ↗')}{link('https://instagram.com/zo.trades2','Brandon / @zo.trades2 ↗')}</div></div><nav aria-label="Service pages"><h3>What we do</h3>{services}</nav><nav aria-label="Agency resources"><h3>Start here</h3>{link(prefix+'index.html#portfolio','Work & ventures')}{link(prefix+'index.html#team','Meet the founders')}{link(prefix+'how-we-work/','How we work')}{link(prefix+'how-we-work/#boundaries','What’s outside scope')}{link(prefix+'guides/','Guides & project planning')}</nav></div>
<details class="footer-docs"><summary>All documentation <span>Plans, scope & delivery notes ↗</span></summary><nav aria-label="All documentation">{docs}{link('https://github.com/AetherAI3/Blackstar','Repository & README')}</nav><p>Planning documents describe proposed systems and working defaults. Your project’s signed scope defines the actual agreement.</p></details>
<div class="footer-bottom"><p>© 2026 Black Star Entertainment. All rights reserved.</p><span>INDEPENDENT. BY DESIGN.</span>{link(prefix+'index.html#hero','Back to home ↑')}</div></div></footer>'''
def metadata(title,desc,url):
 return f'''<link rel="canonical" href="{url}"><meta property="og:type" content="website"><meta property="og:site_name" content="Black Star Entertainment"><meta property="og:title" content="{e(title,quote=True)}"><meta property="og:description" content="{e(desc,quote=True)}"><meta property="og:url" content="{url}"><meta property="og:image" content="{BASE}assets/black-star-aurora.webp"><meta property="og:image:alt" content="Black Star’s dark gold and purple ambient artwork"><meta name="twitter:card" content="summary_large_image">'''
def page(path,title,desc,body,label):
 prefix='../'*len(Path(path).parts)
 url=BASE+path+'/'
 schema={'@context':'https://schema.org','@type':'WebPage','name':title,'description':desc,'url':url,'isPartOf':{'@type':'WebSite','name':'Black Star Entertainment','url':BASE}}
 crumbs={'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Home','item':BASE},{'@type':'ListItem','position':2,'name':label,'item':url}]}
 html=f'''<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="theme-color" content="#0a0a0b"><title>{e(title)}</title><meta name="description" content="{e(desc,quote=True)}">{metadata(title,desc,url)}<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400;1,500&amp;family=Inter:wght@400;500;600;700&amp;display=swap" rel="stylesheet"><link rel="icon" href="{prefix}assets/black-star-icon.svg" type="image/svg+xml"><link rel="stylesheet" href="{prefix}styles.css?v={VERSION}"><script src="{prefix}shared.js?v={VERSION}" defer></script><script src="{prefix}guide.js?v={VERSION}" defer></script><script type="application/ld+json">{json.dumps([schema,crumbs])}</script></head><body class="detail-page"><a class="skip-link" href="#main">Skip to content</a>{header(prefix)}<main id="main"><div class="container breadcrumb"><nav aria-label="Breadcrumb">{link(prefix+'index.html','Home')}<span aria-hidden="true"> / </span><span>{e(label)}</span></nav></div>{body}</main>{footer(prefix)}{guide(prefix)}</body></html>'''
 target=ROOT/path/'index.html';target.parent.mkdir(parents=True,exist_ok=True);target.write_text(html)
def cards(items):
 return '<div class="detail-grid">'+''.join(f'<article class="detail-card"><h3>{e(t)}</h3><p>{e(d)}</p></article>' for t,d in items)+'</div>'
def section(title,body,id=''):
 return f'<section class="detail-section"'+(f' id="{id}"' if id else '')+f' data-ambient>{AMBIENT}<div class="container"><h2>{title}</h2>{body}</div></section>'
for i,s in enumerate(SERVICES,1):
 prefix='../../';contact=prefix+'index.html?service='+s['key']+'#contact'
 proofurl=s['proofurl'].replace('../index.html',prefix+'index.html')
 body=f'''<section class="detail-hero" data-ambient>{AMBIENT}<div class="container"><p class="eyebrow">{e(s['title'])}</p><h1>{e(s['headline'])}</h1><p class="detail-lead">{e(s['intro'])}</p><div class="hero-cta-group">{link(contact,'Discuss your project ↗','btn btn-gold')}{link(prefix+'how-we-work/','How we work →','text-link')}</div><p class="detail-owner">{e(s['owner'])}</p></div></section>'''
 body+=section('Is this a fit?',f'<p class="detail-lead">{e(s["fit"])}</p>')
 body+=section('What we can deliver',cards(s['outputs'])+'<p class="detail-note">These are examples. Your proposal lists the exact deliverables, review rounds, cost, and timing.</p>')
 body+=section('What’s outside the default scope','<ul class="boundary-list">'+''.join('<li>'+e(x)+'</li>' for x in s['boundaries'])+'</ul>','boundaries')
 body+=section('From the brief to your handoff',cards([('The process',s['process']),('What you leave with',s['handoff'])]))
 body+=section('A direct look at the team’s work',f'<div class="proof-note"><p>{e(s["prooftext"])}</p>{link(proofurl,s["proof"]+' ↗','text-link')}</div>')
 body+=section('A few useful answers','<div class="faq-list">'+''.join(f'<details><summary>{e(q)}</summary><p>{e(a)}</p></details>' for q,a in s['faqs'])+'</div>')
 body+=section('Find the right mix','<div class="related-links">'+''.join(link('../'+x['slug']+'/',x['title']+' →','resource-pill') for x in SERVICES if x!=s)+'</div>')
 page('services/'+s['slug'],s['title']+' | Black Star',s['description'],body,s['title'])
body=f'<section class="detail-hero" data-ambient>{AMBIENT}<div class="container"><p class="eyebrow">A SMALL TEAM. A CLEAR PROCESS.</p><h1>Good work starts<br><em>with clear expectations.</em></h1><p class="detail-lead">We’re an independent freelance agency combining creative production and development. You work directly with Edwin and Brandon, from the first brief to the final handoff.</p>{link("../index.html#contact","Tell us what you need ↗","btn btn-gold")}</div></section>'
body+=section('Who does what',cards([('Brandon / development & billing','Websites, apps, backend systems, integrations, deployment, and billing operations. Your technical scope is agreed before the build.'),('Edwin / creative production','Brand direction, photography, video, and content. Your creative scope names the outputs, review rounds, and usage.'),('One lead for your project','For mixed work, we name one project lead. You have a clear contact and a clear next step.')]))
body+=section('Four steps. One shared brief.',cards([('Talk it through','Tell us your goal, timing, budget range, and what you already have. We check whether the work fits.'),('Agree the scope','We list deliverables, exclusions, review rounds, costs, and dependencies in a proposal. Booking follows the agreed contract and payment terms.'),('Make and review','We share the work at agreed milestones. Your named approver brings one consolidated feedback list for each round.'),('Verify and hand over','We check the agreed requirements, obtain approval, and provide the contracted files, access, instructions, and support details.')]))
body+=section('What we do — and what we don’t','<p class="detail-lead">We take on defined creative and technical work. Clear boundaries make it easier to deliver well.</p>'+cards([('Focused engagements','A website, an asset batch, an integration, or a coordinated launch. We agree the actual output rather than promising unlimited work.'),('No automatic extras','New features, additional shoots, new directions after approval, and ongoing support need an agreed scope change or separate phase.'),('No invented guarantees','We do not promise viral content, a search ranking, a sales result, or flawless AI output. We define and verify what we can deliver.'),('No assumed 24/7 team','Availability, response windows, and maintenance are agreed explicitly. We do not present a two-founder agency as a staffed support center.')]),'boundaries')
body+=section('Revisions, changes & corrections','<p class="detail-lead">Our proposed starting point is two consolidated creative revision rounds on the selected direction. Your signed scope sets the actual allowance.</p><p class="reading-copy">A software defect is a failure to meet an agreed requirement; correcting it does not use a design revision. A new feature or changed requirement gets a separate estimate. We confirm price and schedule impact before starting added work.</p>')
body+=section('What a complete handoff means',cards([('The agreed result','Approved files or working pages, with checks tied to your scope and clear notes on any accepted limitations.'),('Access and instructions','The agreed accounts, source files, licenses, and a usable operating guide. Ownership and recurring costs are documented.'),('A clear next chapter','Support dates and contact, plus a separate scope for future changes or recurring care.')]))
body+=section('Proof you can inspect','<p class="detail-lead">Our portfolio currently shows work and ventures behind the founders. We identify that relationship clearly and share relevant examples during scoping.</p><p class="reading-copy">We don’t invent client logos, testimonials, or performance results. Public case studies require permission and evidence for the claims they make.</p>'+link('../index.html#portfolio','Explore work & ventures ↗','text-link'))
body+=section('Before we start','<div class="faq-list"><details><summary>How much will my project cost?</summary><p>We quote after understanding the deliverables, complexity, and dependencies. The contact form’s budget ranges help start that discussion; they are not fixed package prices.</p></details><details><summary>Do you have a client portal?</summary><p>A portal for assets, reviews, and invoices is planned. It is not live yet. We agree the actual review and delivery tools for your project.</p></details><details><summary>Does the contact form send directly?</summary><p>It currently prepares a draft in your email app. Review and send it there, or copy your brief and contact either founder directly.</p></details><details><summary>Where do you work?</summary><p>We have East Coast roots and collaborate remotely. Shoot locations, travel, and dates are confirmed for each production.</p></details></div>')
page('how-we-work','How we work | Black Star','Meet the two founders, understand our freelance agency process, and see how scope, revisions, project changes, and handoffs work.',body,'How we work')
body=f'<section class="detail-hero" data-ambient>{AMBIENT}<div class="container"><p class="eyebrow">KNOW WHAT COMES NEXT</p><h1>A little clarity.<br><em>A better start.</em></h1><p class="detail-lead">New here? Start with how we work, then explore the service you need. Our planning documents are also open if you want a closer look.</p>{link("../how-we-work/","Start with how we work →","btn btn-gold")}</div></section>'
body+=section('Find your service','<div class="guide-directory">'+''.join(f'<a class="detail-card" href="../services/{s["slug"]}/"><h3>{e(s["title"])} →</h3><p>{e(s["intro"])}</p></a>' for s in SERVICES)+'</div>')
body+=section('The open documentation','<p class="detail-lead">These are specifications, working templates, and dated records. Proposed systems are not live features, and planning defaults do not replace your signed project scope.</p><div class="guide-directory">'+''.join(f'<a class="detail-card" href="https://github.com/AetherAI3/Blackstar/blob/main/{path}"><span class="doc-label">GITHUB DOCUMENT ↗</span><h3>{e(title)}</h3><p>{e(desc)}</p></a>' for title,path,desc in DOCS)+'</div>')
page('guides','Project guides & documentation | Black Star','Understand Black Star’s services, project process, scope boundaries, and delivery plans. Plain-language guidance with links to the agency’s open specifications.',body,'Guides & documentation')
# Keep the homepage content and all its personal links intact while replacing shared navigation/footer blocks.
p=ROOT/'index.html';home=p.read_text()
home=re.sub(r'<header class="site-header".*?</header>',lambda _:header(''),home,flags=re.S)
home=re.sub(r'<aside class="project-guide".*?</aside>',lambda _:guide(''),home,flags=re.S)
home=re.sub(r'<footer id="footer".*?</footer>',lambda _:footer(''),home,flags=re.S)
for s in SERVICES:
 pattern=r'(<article class="service-card" id="service-'+s['key']+r'">)(.*?)(</article>)'
 def add_detail(m):
  inner=re.sub(r'<a [^>]*class="service-detail-link"[^>]*>.*?</a>','',m.group(2),flags=re.S)
  return m.group(1)+inner+link('services/'+s['slug']+'/', 'Explore '+s['title'].lower()+' →','service-detail-link')+m.group(3)
 home=re.sub(pattern,add_detail,home,flags=re.S)
home=re.sub(r'v=(project-guide-1|service-foundation-\d+|nav-guide-\d+|soft-motion-\d+)','v='+VERSION,home)
if 'src="guide.js' not in home: home=home.replace('<script src="script.js',f'<script src="guide.js?v={VERSION}" defer></script>\n<script src="script.js')
if 'src="shared.js' not in home: home=home.replace('<script src="script.js',f'<script src="shared.js?v={VERSION}" defer></script>\n<script src="script.js')
home=re.sub(r'<!-- search foundation -->.*?<!-- /search foundation -->\n?','',home,flags=re.S)
org={'@context':'https://schema.org','@type':'Organization','name':'Black Star Entertainment','url':BASE,'logo':BASE+'assets/black-star-logo.svg','description':'Independent creative and digital agency led by Edwin and Brandon.'}
head='<!-- search foundation -->'+metadata('Black Star Entertainment — Creative & Digital Agency','Websites, branding, photography, video, social content, and automation. Work directly with Edwin and Brandon on a clearly scoped freelance project.',BASE)+'<script type="application/ld+json">'+json.dumps(org)+'</script><!-- /search foundation -->'
home=home.replace('</head>',head+'\n</head>');p.write_text(home)
paths=['']+['services/'+s['slug']+'/' for s in SERVICES]+['how-we-work/','guides/']
(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join('<url><loc>'+BASE+x+'</loc></url>\n' for x in paths)+'</urlset>\n')
print('Generated eight content pages, nine sitemap URLs, and shared footer links.')
